project_id = "ltdbdamencicjnwfqvkm"

[functions.send-notification]
verify_jwt = true

[functions.intasend-payment]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = false

[functions.admin-operations]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
